name: on-push

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test:
    name: test - run unitest on action
    runs-on: ubuntu-latest
    container: golang:1.18
    services:
      novellist:
        image: novellist:latest
        env:
          NOVELLIST_DB: novellist
          NOVELLIST_PASSWORD: 123456
          NOVELLIST_PORT: 3306
          NOVELLIST_USER: azifaazka
        ports:
          - 3306:3306
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v2
      - name: running unitest
        env:
          DB_USER: azifaazka
          DB_HOST: root
          DB_PORT: 3306
          DB_PASS: 123456
          DB_NAME: novellist
        run: |
          go mod tidy
          go test ./... -cover -failfast